####### User Profile API ######
GET http://localhost:3000/profile

######## Create User Profile ########

POST http://localhost:3000/profile
Content-Type: application/json

{
  "username": "user1 ",
  "password": "1234",
  "cardId": "1234567274222",
  "mobile": "0919554633"
 
}




